// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deploy_intents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployIntent = `-- name: CreateDeployIntent :one
INSERT INTO deploy_intents (
    delivery_id, stack_index, repo, git_ref, sha,
    image, tag, stack, services, environment,
    deployment_id, installation_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at
`

type CreateDeployIntentParams struct {
	DeliveryID     string   `json:"delivery_id"`
	StackIndex     int32    `json:"stack_index"`
	Repo           string   `json:"repo"`
	GitRef         string   `json:"git_ref"`
	Sha            string   `json:"sha"`
	Image          string   `json:"image"`
	Tag            string   `json:"tag"`
	Stack          string   `json:"stack"`
	Services       []string `json:"services"`
	Environment    string   `json:"environment"`
	DeploymentID   int64    `json:"deployment_id"`
	InstallationID int64    `json:"installation_id"`
}

func (q *Queries) CreateDeployIntent(ctx context.Context, arg CreateDeployIntentParams) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, createDeployIntent,
		arg.DeliveryID,
		arg.StackIndex,
		arg.Repo,
		arg.GitRef,
		arg.Sha,
		arg.Image,
		arg.Tag,
		arg.Stack,
		arg.Services,
		arg.Environment,
		arg.DeploymentID,
		arg.InstallationID,
	)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeployIntent = `-- name: DeleteDeployIntent :exec
DELETE FROM deploy_intents
WHERE id = $1
`

func (q *Queries) DeleteDeployIntent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeployIntent, id)
	return err
}

const getDeployIntent = `-- name: GetDeployIntent :one
SELECT id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at FROM deploy_intents
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeployIntent(ctx context.Context, id pgtype.UUID) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, getDeployIntent, id)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementDeployIntentAttempts = `-- name: IncrementDeployIntentAttempts :one
UPDATE deploy_intents
SET attempts = attempts + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at
`

func (q *Queries) IncrementDeployIntentAttempts(ctx context.Context, id pgtype.UUID) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, incrementDeployIntentAttempts, id)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeployIntentsByStatus = `-- name: ListDeployIntentsByStatus :many
SELECT id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at FROM deploy_intents
WHERE status = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDeployIntentsByStatus(ctx context.Context, status string) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, listDeployIntentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.StackIndex,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Image,
			&i.Tag,
			&i.Stack,
			&i.Services,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeployIntentStatus = `-- name: UpdateDeployIntentStatus :one
UPDATE deploy_intents
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at
`

type UpdateDeployIntentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDeployIntentStatus(ctx context.Context, arg UpdateDeployIntentStatusParams) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, updateDeployIntentStatus, arg.ID, arg.Status)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
