// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDeployIntent(ctx context.Context, arg CreateDeployIntentParams) (DeployIntent, error)
	DeleteDeployIntent(ctx context.Context, id pgtype.UUID) error
	GetDeployIntent(ctx context.Context, id pgtype.UUID) (DeployIntent, error)
	IncrementDeployIntentAttempts(ctx context.Context, id pgtype.UUID) (DeployIntent, error)
	ListDeployIntentsByStatus(ctx context.Context, status string) ([]DeployIntent, error)
	UpdateDeployIntentStatus(ctx context.Context, arg UpdateDeployIntentStatusParams) (DeployIntent, error)
}

var _ Querier = (*Queries)(nil)
