// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgent = `-- name: GetAgent :one
SELECT id, name, compose_file, remote_ip, last_seen_at, created_at, updated_at, project_id FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ComposeFile,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, compose_file, remote_ip, last_seen_at, created_at, updated_at, project_id FROM agents ORDER BY name ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ComposeFile,
			&i.RemoteIp,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO agents (name, compose_file, remote_ip, last_seen_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (name)
DO UPDATE SET
    compose_file  = EXCLUDED.compose_file,
    remote_ip     = EXCLUDED.remote_ip,
    last_seen_at  = NOW(),
    updated_at    = NOW()
RETURNING id, name, compose_file, remote_ip, last_seen_at, created_at, updated_at, project_id
`

type UpsertAgentParams struct {
	Name        string `json:"name"`
	ComposeFile string `json:"compose_file"`
	RemoteIp    string `json:"remote_ip"`
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, upsertAgent, arg.Name, arg.ComposeFile, arg.RemoteIp)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ComposeFile,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}
