// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindAgentToProject = `-- name: BindAgentToProject :one
UPDATE agents
SET project_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type
`

type BindAgentToProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) BindAgentToProject(ctx context.Context, arg BindAgentToProjectParams) (Agent, error) {
	row := q.db.QueryRow(ctx, bindAgentToProject, arg.ID, arg.ProjectID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
	)
	return i, err
}

const clearAgentProjectBinding = `-- name: ClearAgentProjectBinding :exec
UPDATE agents
SET project_id = NULL,
    updated_at = NOW()
WHERE project_id = $1
`

func (q *Queries) ClearAgentProjectBinding(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearAgentProjectBinding, projectID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type FROM agents WHERE name = $1
`

func (q *Queries) GetAgentByName(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByName, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type FROM agents ORDER BY name ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RemoteIp,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.AgentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO agents (name, remote_ip, agent_type, last_seen_at)
VALUES ($1, $2, NULLIF($3::text, ''), NOW())
ON CONFLICT (name)
DO UPDATE SET
    remote_ip     = EXCLUDED.remote_ip,
    agent_type    = COALESCE(EXCLUDED.agent_type, agents.agent_type),
    last_seen_at  = NOW(),
    updated_at    = NOW()
RETURNING id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type
`

type UpsertAgentParams struct {
	Name      string `json:"name"`
	RemoteIp  string `json:"remote_ip"`
	AgentType string `json:"agent_type"`
}

// agent_type is passed in (empty string treated as NULL). On conflict we
// preserve the existing type when the caller didn't send one, so an old
// agent reconnecting without the header doesn't wipe a known type.
func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, upsertAgent, arg.Name, arg.RemoteIp, arg.AgentType)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
	)
	return i, err
}
