// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindAgentToProject = `-- name: BindAgentToProject :one
UPDATE agents
SET project_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type, version, token_hash, installed_by_user_id, cpu_percent, mem_used_bytes, mem_total_bytes, swap_used_bytes, swap_total_bytes, disk_used_bytes, disk_total_bytes
`

type BindAgentToProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) BindAgentToProject(ctx context.Context, arg BindAgentToProjectParams) (Agent, error) {
	row := q.db.QueryRow(ctx, bindAgentToProject, arg.ID, arg.ProjectID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
		&i.Version,
		&i.TokenHash,
		&i.InstalledByUserID,
		&i.CpuPercent,
		&i.MemUsedBytes,
		&i.MemTotalBytes,
		&i.SwapUsedBytes,
		&i.SwapTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
	)
	return i, err
}

const clearAgentProjectBinding = `-- name: ClearAgentProjectBinding :exec
UPDATE agents
SET project_id = NULL,
    updated_at = NOW()
WHERE project_id = $1
`

func (q *Queries) ClearAgentProjectBinding(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearAgentProjectBinding, projectID)
	return err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, installed_by_user_id, token_hash, remote_ip)
VALUES ($1, $2, $3, '')
RETURNING id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type, version, token_hash, installed_by_user_id, cpu_percent, mem_used_bytes, mem_total_bytes, swap_used_bytes, swap_total_bytes, disk_used_bytes, disk_total_bytes
`

type CreateAgentParams struct {
	Name              string      `json:"name"`
	InstalledByUserID pgtype.UUID `json:"installed_by_user_id"`
	TokenHash         pgtype.Text `json:"token_hash"`
}

// Pre-provision an agent. token_hash is sha256(raw token); the raw token is
// returned to the caller once and never stored. Fails on duplicate name.
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.Name, arg.InstalledByUserID, arg.TokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
		&i.Version,
		&i.TokenHash,
		&i.InstalledByUserID,
		&i.CpuPercent,
		&i.MemUsedBytes,
		&i.MemTotalBytes,
		&i.SwapUsedBytes,
		&i.SwapTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :execrows
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT a.id, a.name, a.remote_ip, a.last_seen_at, a.created_at, a.updated_at, a.project_id, a.agent_type, a.version, a.token_hash, a.installed_by_user_id, a.cpu_percent, a.mem_used_bytes, a.mem_total_bytes, a.swap_used_bytes, a.swap_total_bytes, a.disk_used_bytes, a.disk_total_bytes, p.name AS project_name
FROM agents a
LEFT JOIN projects p ON p.id = a.project_id
WHERE a.id = $1
`

type GetAgentRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	RemoteIp          string             `json:"remote_ip"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	AgentType         pgtype.Text        `json:"agent_type"`
	Version           pgtype.Text        `json:"version"`
	TokenHash         pgtype.Text        `json:"token_hash"`
	InstalledByUserID pgtype.UUID        `json:"installed_by_user_id"`
	CpuPercent        pgtype.Float4      `json:"cpu_percent"`
	MemUsedBytes      pgtype.Int8        `json:"mem_used_bytes"`
	MemTotalBytes     pgtype.Int8        `json:"mem_total_bytes"`
	SwapUsedBytes     pgtype.Int8        `json:"swap_used_bytes"`
	SwapTotalBytes    pgtype.Int8        `json:"swap_total_bytes"`
	DiskUsedBytes     pgtype.Int8        `json:"disk_used_bytes"`
	DiskTotalBytes    pgtype.Int8        `json:"disk_total_bytes"`
	ProjectName       pgtype.Text        `json:"project_name"`
}

func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
		&i.Version,
		&i.TokenHash,
		&i.InstalledByUserID,
		&i.CpuPercent,
		&i.MemUsedBytes,
		&i.MemTotalBytes,
		&i.SwapUsedBytes,
		&i.SwapTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
		&i.ProjectName,
	)
	return i, err
}

const getAgentByTokenHash = `-- name: GetAgentByTokenHash :one
SELECT id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type, version, token_hash, installed_by_user_id, cpu_percent, mem_used_bytes, mem_total_bytes, swap_used_bytes, swap_total_bytes, disk_used_bytes, disk_total_bytes FROM agents WHERE token_hash = $1
`

func (q *Queries) GetAgentByTokenHash(ctx context.Context, tokenHash pgtype.Text) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByTokenHash, tokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
		&i.Version,
		&i.TokenHash,
		&i.InstalledByUserID,
		&i.CpuPercent,
		&i.MemUsedBytes,
		&i.MemTotalBytes,
		&i.SwapUsedBytes,
		&i.SwapTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
	)
	return i, err
}

const listAgentsForUser = `-- name: ListAgentsForUser :many
SELECT a.id, a.name, a.remote_ip, a.last_seen_at, a.created_at, a.updated_at, a.project_id, a.agent_type, a.version, a.token_hash, a.installed_by_user_id, a.cpu_percent, a.mem_used_bytes, a.mem_total_bytes, a.swap_used_bytes, a.swap_total_bytes, a.disk_used_bytes, a.disk_total_bytes, p.name AS project_name
FROM agents a
LEFT JOIN projects p ON p.id = a.project_id
WHERE (a.project_id IS NULL AND a.installed_by_user_id = $1)
   OR a.project_id IN (
        SELECT pr.id
        FROM projects pr
        LEFT JOIN project_members pm ON pm.project_id = pr.id AND pm.user_id = $1
        WHERE pr.user_id = $1 OR pm.user_id = $1
   )
ORDER BY a.name ASC
`

type ListAgentsForUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	RemoteIp          string             `json:"remote_ip"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	AgentType         pgtype.Text        `json:"agent_type"`
	Version           pgtype.Text        `json:"version"`
	TokenHash         pgtype.Text        `json:"token_hash"`
	InstalledByUserID pgtype.UUID        `json:"installed_by_user_id"`
	CpuPercent        pgtype.Float4      `json:"cpu_percent"`
	MemUsedBytes      pgtype.Int8        `json:"mem_used_bytes"`
	MemTotalBytes     pgtype.Int8        `json:"mem_total_bytes"`
	SwapUsedBytes     pgtype.Int8        `json:"swap_used_bytes"`
	SwapTotalBytes    pgtype.Int8        `json:"swap_total_bytes"`
	DiskUsedBytes     pgtype.Int8        `json:"disk_used_bytes"`
	DiskTotalBytes    pgtype.Int8        `json:"disk_total_bytes"`
	ProjectName       pgtype.Text        `json:"project_name"`
}

// Visibility: an unbound agent is seen only by its installer; once bound, by
// members of its project (owner or project_members row).
func (q *Queries) ListAgentsForUser(ctx context.Context, installedByUserID pgtype.UUID) ([]ListAgentsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForUser, installedByUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsForUserRow{}
	for rows.Next() {
		var i ListAgentsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RemoteIp,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.AgentType,
			&i.Version,
			&i.TokenHash,
			&i.InstalledByUserID,
			&i.CpuPercent,
			&i.MemUsedBytes,
			&i.MemTotalBytes,
			&i.SwapUsedBytes,
			&i.SwapTotalBytes,
			&i.DiskUsedBytes,
			&i.DiskTotalBytes,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentToken = `-- name: SetAgentToken :one
UPDATE agents
SET token_hash = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, remote_ip, last_seen_at, created_at, updated_at, project_id, agent_type, version, token_hash, installed_by_user_id, cpu_percent, mem_used_bytes, mem_total_bytes, swap_used_bytes, swap_total_bytes, disk_used_bytes, disk_total_bytes
`

type SetAgentTokenParams struct {
	ID        pgtype.UUID `json:"id"`
	TokenHash pgtype.Text `json:"token_hash"`
}

// Re-issue: replace the stored digest with a fresh one (migration / loss recovery).
func (q *Queries) SetAgentToken(ctx context.Context, arg SetAgentTokenParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentToken, arg.ID, arg.TokenHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RemoteIp,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.AgentType,
		&i.Version,
		&i.TokenHash,
		&i.InstalledByUserID,
		&i.CpuPercent,
		&i.MemUsedBytes,
		&i.MemTotalBytes,
		&i.SwapUsedBytes,
		&i.SwapTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
	)
	return i, err
}

const touchAgent = `-- name: TouchAgent :exec
UPDATE agents
SET remote_ip        = $2,
    agent_type       = COALESCE(NULLIF($3::text, ''), agent_type),
    version          = COALESCE(NULLIF($4::text, ''), version),
    cpu_percent      = COALESCE($5::real, cpu_percent),
    mem_used_bytes   = COALESCE($6::bigint, mem_used_bytes),
    mem_total_bytes  = COALESCE($7::bigint, mem_total_bytes),
    swap_used_bytes  = COALESCE($8::bigint, swap_used_bytes),
    swap_total_bytes = COALESCE($9::bigint, swap_total_bytes),
    disk_used_bytes  = COALESCE($10::bigint, disk_used_bytes),
    disk_total_bytes = COALESCE($11::bigint, disk_total_bytes),
    last_seen_at = NOW(),
    updated_at   = NOW()
WHERE id = $1
`

type TouchAgentParams struct {
	ID             pgtype.UUID   `json:"id"`
	RemoteIp       string        `json:"remote_ip"`
	AgentType      string        `json:"agent_type"`
	Version        string        `json:"version"`
	CpuPercent     pgtype.Float4 `json:"cpu_percent"`
	MemUsedBytes   pgtype.Int8   `json:"mem_used_bytes"`
	MemTotalBytes  pgtype.Int8   `json:"mem_total_bytes"`
	SwapUsedBytes  pgtype.Int8   `json:"swap_used_bytes"`
	SwapTotalBytes pgtype.Int8   `json:"swap_total_bytes"`
	DiskUsedBytes  pgtype.Int8   `json:"disk_used_bytes"`
	DiskTotalBytes pgtype.Int8   `json:"disk_total_bytes"`
}

// Heartbeat on the agent already resolved from its token. Empty agent_type or
// version preserves the existing value so a poll without the header can't wipe
// it; NULL metrics likewise keep the last reported values.
func (q *Queries) TouchAgent(ctx context.Context, arg TouchAgentParams) error {
	_, err := q.db.Exec(ctx, touchAgent,
		arg.ID,
		arg.RemoteIp,
		arg.AgentType,
		arg.Version,
		arg.CpuPercent,
		arg.MemUsedBytes,
		arg.MemTotalBytes,
		arg.SwapUsedBytes,
		arg.SwapTotalBytes,
		arg.DiskUsedBytes,
		arg.DiskTotalBytes,
	)
	return err
}
