// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, token_hash)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, token_hash, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.UserID, arg.Name, arg.TokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKeyForUser = `-- name: DeleteAPIKeyForUser :one
DELETE FROM api_keys WHERE id = $1 AND user_id = $2 RETURNING id, user_id, name, token_hash, last_used_at, created_at
`

type DeleteAPIKeyForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIKeyForUser(ctx context.Context, arg DeleteAPIKeyForUserParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, deleteAPIKeyForUser, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByTokenHash = `-- name: GetAPIKeyByTokenHash :one
SELECT id, user_id, name, token_hash, last_used_at, created_at FROM api_keys WHERE token_hash = $1
`

func (q *Queries) GetAPIKeyByTokenHash(ctx context.Context, tokenHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByTokenHash, tokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, token_hash, last_used_at, created_at FROM api_keys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < NOW() - INTERVAL '1 minute')
`

// Throttled to one write per minute so a busy key doesn't write on every request.
func (q *Queries) TouchAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
