// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deploy_intents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeDeployIntent = `-- name: CompleteDeployIntent :one
UPDATE deploy_intents
SET status = $1,
    updated_at = NOW()
WHERE id = $2 AND status = 'dispatched'
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at
`

type CompleteDeployIntentParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteDeployIntent(ctx context.Context, arg CompleteDeployIntentParams) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, completeDeployIntent, arg.Status, arg.ID)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
	)
	return i, err
}

const countDeployIntentsByStatus = `-- name: CountDeployIntentsByStatus :one
SELECT count(*) FROM deploy_intents WHERE status = $1
`

func (q *Queries) CountDeployIntentsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countDeployIntentsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployIntent = `-- name: CreateDeployIntent :one
INSERT INTO deploy_intents (
    delivery_id, stack_index, repo, git_ref, sha,
    image, tag, stack, services, environment,
    deployment_id, installation_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
ON CONFLICT (delivery_id, stack_index) DO NOTHING
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at
`

type CreateDeployIntentParams struct {
	DeliveryID     string   `json:"delivery_id"`
	StackIndex     int32    `json:"stack_index"`
	Repo           string   `json:"repo"`
	GitRef         string   `json:"git_ref"`
	Sha            string   `json:"sha"`
	Image          string   `json:"image"`
	Tag            string   `json:"tag"`
	Stack          string   `json:"stack"`
	Services       []string `json:"services"`
	Environment    string   `json:"environment"`
	DeploymentID   int64    `json:"deployment_id"`
	InstallationID int64    `json:"installation_id"`
}

// Webhook redeliveries dedup on (delivery_id, stack_index): on conflict the
// insert is skipped and sqlc returns pgx.ErrNoRows, which callers treat as
// "already enqueued, do nothing".
func (q *Queries) CreateDeployIntent(ctx context.Context, arg CreateDeployIntentParams) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, createDeployIntent,
		arg.DeliveryID,
		arg.StackIndex,
		arg.Repo,
		arg.GitRef,
		arg.Sha,
		arg.Image,
		arg.Tag,
		arg.Stack,
		arg.Services,
		arg.Environment,
		arg.DeploymentID,
		arg.InstallationID,
	)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
	)
	return i, err
}

const failTimedOutIntents = `-- name: FailTimedOutIntents :many
UPDATE deploy_intents
SET status = 'permanently_failed',
    updated_at = NOW()
WHERE status = 'dispatched'
  AND dispatched_at < $1
  AND attempts >= $2
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at
`

type FailTimedOutIntentsParams struct {
	Cutoff      pgtype.Timestamp `json:"cutoff"`
	MaxAttempts int32            `json:"max_attempts"`
}

func (q *Queries) FailTimedOutIntents(ctx context.Context, arg FailTimedOutIntentsParams) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, failTimedOutIntents, arg.Cutoff, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.StackIndex,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Image,
			&i.Tag,
			&i.Stack,
			&i.Services,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployIntentsByStatus = `-- name: ListDeployIntentsByStatus :many
SELECT id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at FROM deploy_intents
WHERE status = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDeployIntentsByStatus(ctx context.Context, status string) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, listDeployIntentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.StackIndex,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Image,
			&i.Tag,
			&i.Stack,
			&i.Services,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueDeployIntent = `-- name: RequeueDeployIntent :one
UPDATE deploy_intents
SET status = 'created',
    dispatched_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND status = 'dispatched'
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at
`

func (q *Queries) RequeueDeployIntent(ctx context.Context, id pgtype.UUID) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, requeueDeployIntent, id)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
	)
	return i, err
}

const requeueTimedOutIntents = `-- name: RequeueTimedOutIntents :many
UPDATE deploy_intents
SET status = 'created',
    dispatched_at = NULL,
    updated_at = NOW()
WHERE status = 'dispatched'
  AND dispatched_at < $1
  AND attempts < $2
RETURNING id, delivery_id, stack_index, repo, git_ref, sha, image, tag, stack, services, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at
`

type RequeueTimedOutIntentsParams struct {
	Cutoff      pgtype.Timestamp `json:"cutoff"`
	MaxAttempts int32            `json:"max_attempts"`
}

func (q *Queries) RequeueTimedOutIntents(ctx context.Context, arg RequeueTimedOutIntentsParams) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, requeueTimedOutIntents, arg.Cutoff, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.StackIndex,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Image,
			&i.Tag,
			&i.Stack,
			&i.Services,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeNextDeployIntent = `-- name: TakeNextDeployIntent :one
WITH candidate AS (
    SELECT id
    FROM deploy_intents
    WHERE status = 'created'
      AND stack NOT IN (
          SELECT DISTINCT stack FROM deploy_intents WHERE status = 'dispatched'
      )
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE deploy_intents di
SET status = 'dispatched',
    attempts = attempts + 1,
    dispatched_at = NOW(),
    updated_at = NOW()
FROM candidate c
WHERE di.id = c.id
RETURNING di.id, di.delivery_id, di.stack_index, di.repo, di.git_ref, di.sha, di.image, di.tag, di.stack, di.services, di.environment, di.deployment_id, di.installation_id, di.status, di.attempts, di.created_at, di.updated_at, di.dispatched_at
`

// Atomically claim the oldest dispatchable intent. The CTE skips stacks that
// already have a dispatched intent (concurrency guard) and uses FOR UPDATE
// SKIP LOCKED so concurrent callers don't block each other.
func (q *Queries) TakeNextDeployIntent(ctx context.Context) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, takeNextDeployIntent)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.StackIndex,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Image,
		&i.Tag,
		&i.Stack,
		&i.Services,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
	)
	return i, err
}
