// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deploy_intents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeDeployIntent = `-- name: CompleteDeployIntent :one
UPDATE deploy_intents
SET status = $1,
    updated_at = NOW()
WHERE id = $2 AND status = 'dispatched'
RETURNING id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file
`

type CompleteDeployIntentParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) CompleteDeployIntent(ctx context.Context, arg CompleteDeployIntentParams) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, completeDeployIntent, arg.Status, arg.ID)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Stack,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
		&i.ServicesSpec,
		&i.ProjectID,
		&i.ComposeFile,
	)
	return i, err
}

const countDeployIntentsByStatus = `-- name: CountDeployIntentsByStatus :one
SELECT count(*) FROM deploy_intents WHERE status = $1
`

func (q *Queries) CountDeployIntentsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countDeployIntentsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeployIntentsForUser = `-- name: CountDeployIntentsForUser :one
SELECT count(*)
FROM deploy_intents di
JOIN projects p ON p.id = di.project_id
LEFT JOIN project_members pm
  ON pm.project_id = p.id AND pm.user_id = $1
WHERE (p.user_id = $1 OR pm.user_id = $1)
  AND ($2::text IS NULL OR di.status = $2)
  AND ($3::uuid IS NULL OR di.project_id = $3)
  AND ($4::text IS NULL OR di.repo ILIKE '%' || $4 || '%')
  AND ($5::text IS NULL OR di.environment = $5)
`

type CountDeployIntentsForUserParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Status      pgtype.Text `json:"status"`
	ProjectID   pgtype.UUID `json:"project_id"`
	Repo        pgtype.Text `json:"repo"`
	Environment pgtype.Text `json:"environment"`
}

func (q *Queries) CountDeployIntentsForUser(ctx context.Context, arg CountDeployIntentsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeployIntentsForUser,
		arg.UserID,
		arg.Status,
		arg.ProjectID,
		arg.Repo,
		arg.Environment,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployIntent = `-- name: CreateDeployIntent :one
INSERT INTO deploy_intents (
    delivery_id, project_id, repo, git_ref, sha,
    stack, services_spec, environment, compose_file,
    deployment_id, installation_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11
)
ON CONFLICT (delivery_id, project_id) WHERE project_id IS NOT NULL DO NOTHING
RETURNING id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file
`

type CreateDeployIntentParams struct {
	DeliveryID     string      `json:"delivery_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Repo           string      `json:"repo"`
	GitRef         string      `json:"git_ref"`
	Sha            string      `json:"sha"`
	Stack          string      `json:"stack"`
	ServicesSpec   []byte      `json:"services_spec"`
	Environment    string      `json:"environment"`
	ComposeFile    string      `json:"compose_file"`
	DeploymentID   int64       `json:"deployment_id"`
	InstallationID int64       `json:"installation_id"`
}

// Webhook redeliveries dedup on (delivery_id, project_id) via the partial
// unique index idx_deploy_intents_delivery_project. On conflict sqlc returns
// pgx.ErrNoRows, which callers treat as "already enqueued, do nothing".
func (q *Queries) CreateDeployIntent(ctx context.Context, arg CreateDeployIntentParams) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, createDeployIntent,
		arg.DeliveryID,
		arg.ProjectID,
		arg.Repo,
		arg.GitRef,
		arg.Sha,
		arg.Stack,
		arg.ServicesSpec,
		arg.Environment,
		arg.ComposeFile,
		arg.DeploymentID,
		arg.InstallationID,
	)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Stack,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
		&i.ServicesSpec,
		&i.ProjectID,
		&i.ComposeFile,
	)
	return i, err
}

const failTimedOutIntents = `-- name: FailTimedOutIntents :many
UPDATE deploy_intents
SET status = 'permanently_failed',
    updated_at = NOW()
WHERE status = 'dispatched'
  AND dispatched_at < $1
  AND attempts >= $2
RETURNING id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file
`

type FailTimedOutIntentsParams struct {
	Cutoff      pgtype.Timestamp `json:"cutoff"`
	MaxAttempts int32            `json:"max_attempts"`
}

func (q *Queries) FailTimedOutIntents(ctx context.Context, arg FailTimedOutIntentsParams) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, failTimedOutIntents, arg.Cutoff, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Stack,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
			&i.ServicesSpec,
			&i.ProjectID,
			&i.ComposeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeployIntentByID = `-- name: GetDeployIntentByID :one
SELECT id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file FROM deploy_intents WHERE id = $1
`

func (q *Queries) GetDeployIntentByID(ctx context.Context, id pgtype.UUID) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, getDeployIntentByID, id)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Stack,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
		&i.ServicesSpec,
		&i.ProjectID,
		&i.ComposeFile,
	)
	return i, err
}

const listDeployIntentsByStatus = `-- name: ListDeployIntentsByStatus :many
SELECT id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file FROM deploy_intents
WHERE status = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDeployIntentsByStatus(ctx context.Context, status string) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, listDeployIntentsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Stack,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
			&i.ServicesSpec,
			&i.ProjectID,
			&i.ComposeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployIntentsForUserPaged = `-- name: ListDeployIntentsForUserPaged :many
SELECT di.id, di.delivery_id, di.repo, di.git_ref, di.sha, di.stack, di.environment, di.deployment_id, di.installation_id, di.status, di.attempts, di.created_at, di.updated_at, di.dispatched_at, di.services_spec, di.project_id, di.compose_file
FROM deploy_intents di
JOIN projects p ON p.id = di.project_id
LEFT JOIN project_members pm
  ON pm.project_id = p.id AND pm.user_id = $1
WHERE (p.user_id = $1 OR pm.user_id = $1)
  AND ($2::text IS NULL OR di.status = $2)
  AND ($3::uuid IS NULL OR di.project_id = $3)
  AND ($4::text IS NULL OR di.repo ILIKE '%' || $4 || '%')
  AND ($5::text IS NULL OR di.environment = $5)
ORDER BY di.created_at DESC
LIMIT $7 OFFSET $6
`

type ListDeployIntentsForUserPagedParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Status      pgtype.Text `json:"status"`
	ProjectID   pgtype.UUID `json:"project_id"`
	Repo        pgtype.Text `json:"repo"`
	Environment pgtype.Text `json:"environment"`
	RowOffset   int32       `json:"row_offset"`
	RowLimit    int32       `json:"row_limit"`
}

// Paged + filtered variant of ListRecentDeployIntentsForUser. Each filter
// param is nullable; NULL means "no filter on this column".
func (q *Queries) ListDeployIntentsForUserPaged(ctx context.Context, arg ListDeployIntentsForUserPagedParams) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, listDeployIntentsForUserPaged,
		arg.UserID,
		arg.Status,
		arg.ProjectID,
		arg.Repo,
		arg.Environment,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Stack,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
			&i.ServicesSpec,
			&i.ProjectID,
			&i.ComposeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeployIntents = `-- name: ListRecentDeployIntents :many
SELECT id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file FROM deploy_intents
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentDeployIntents(ctx context.Context, limit int32) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, listRecentDeployIntents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Stack,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
			&i.ServicesSpec,
			&i.ProjectID,
			&i.ComposeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeployIntentsForUser = `-- name: ListRecentDeployIntentsForUser :many
SELECT di.id, di.delivery_id, di.repo, di.git_ref, di.sha, di.stack, di.environment, di.deployment_id, di.installation_id, di.status, di.attempts, di.created_at, di.updated_at, di.dispatched_at, di.services_spec, di.project_id, di.compose_file
FROM deploy_intents di
JOIN projects p ON p.id = di.project_id
LEFT JOIN project_members pm
  ON pm.project_id = p.id AND pm.user_id = $1
WHERE p.user_id = $1 OR pm.user_id = $1
ORDER BY di.created_at DESC
LIMIT $2
`

type ListRecentDeployIntentsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

// Same as ListRecentDeployIntents but scoped to projects the user can access:
// either owns (projects.user_id) or is a member of (project_members).
func (q *Queries) ListRecentDeployIntentsForUser(ctx context.Context, arg ListRecentDeployIntentsForUserParams) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, listRecentDeployIntentsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Stack,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
			&i.ServicesSpec,
			&i.ProjectID,
			&i.ComposeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueDeployIntent = `-- name: RequeueDeployIntent :one
UPDATE deploy_intents
SET status = 'created',
    dispatched_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND status = 'dispatched'
RETURNING id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file
`

func (q *Queries) RequeueDeployIntent(ctx context.Context, id pgtype.UUID) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, requeueDeployIntent, id)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Stack,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
		&i.ServicesSpec,
		&i.ProjectID,
		&i.ComposeFile,
	)
	return i, err
}

const requeueTimedOutIntents = `-- name: RequeueTimedOutIntents :many
UPDATE deploy_intents
SET status = 'created',
    dispatched_at = NULL,
    updated_at = NOW()
WHERE status = 'dispatched'
  AND dispatched_at < $1
  AND attempts < $2
RETURNING id, delivery_id, repo, git_ref, sha, stack, environment, deployment_id, installation_id, status, attempts, created_at, updated_at, dispatched_at, services_spec, project_id, compose_file
`

type RequeueTimedOutIntentsParams struct {
	Cutoff      pgtype.Timestamp `json:"cutoff"`
	MaxAttempts int32            `json:"max_attempts"`
}

func (q *Queries) RequeueTimedOutIntents(ctx context.Context, arg RequeueTimedOutIntentsParams) ([]DeployIntent, error) {
	rows, err := q.db.Query(ctx, requeueTimedOutIntents, arg.Cutoff, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployIntent{}
	for rows.Next() {
		var i DeployIntent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Repo,
			&i.GitRef,
			&i.Sha,
			&i.Stack,
			&i.Environment,
			&i.DeploymentID,
			&i.InstallationID,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DispatchedAt,
			&i.ServicesSpec,
			&i.ProjectID,
			&i.ComposeFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeNextDeployIntent = `-- name: TakeNextDeployIntent :one
WITH candidate AS (
    SELECT di.id
    FROM deploy_intents di
    JOIN agents a ON a.project_id = di.project_id
    WHERE di.status = 'created'
      AND a.name = $1
      AND di.stack NOT IN (
          SELECT DISTINCT stack FROM deploy_intents WHERE status = 'dispatched'
      )
    ORDER BY di.created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE deploy_intents di
SET status = 'dispatched',
    attempts = attempts + 1,
    dispatched_at = NOW(),
    updated_at = NOW()
FROM candidate c
WHERE di.id = c.id
RETURNING di.id, di.delivery_id, di.repo, di.git_ref, di.sha, di.stack, di.environment, di.deployment_id, di.installation_id, di.status, di.attempts, di.created_at, di.updated_at, di.dispatched_at, di.services_spec, di.project_id, di.compose_file
`

// Claim the oldest dispatchable intent for @agent_name's bound project.
// FOR UPDATE SKIP LOCKED + the dispatched-stack guard keep concurrent
// pollers from blocking each other or double-claiming a stack.
func (q *Queries) TakeNextDeployIntent(ctx context.Context, agentName string) (DeployIntent, error) {
	row := q.db.QueryRow(ctx, takeNextDeployIntent, agentName)
	var i DeployIntent
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.Repo,
		&i.GitRef,
		&i.Sha,
		&i.Stack,
		&i.Environment,
		&i.DeploymentID,
		&i.InstallationID,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DispatchedAt,
		&i.ServicesSpec,
		&i.ProjectID,
		&i.ComposeFile,
	)
	return i, err
}
