// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deploy_mappings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployMapping = `-- name: CreateDeployMapping :one
INSERT INTO deploy_mappings (repo, agent_id, environment, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, repo, agent_id, environment, enabled, created_at, updated_at
`

type CreateDeployMappingParams struct {
	Repo        string      `json:"repo"`
	AgentID     pgtype.UUID `json:"agent_id"`
	Environment string      `json:"environment"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) CreateDeployMapping(ctx context.Context, arg CreateDeployMappingParams) (DeployMapping, error) {
	row := q.db.QueryRow(ctx, createDeployMapping,
		arg.Repo,
		arg.AgentID,
		arg.Environment,
		arg.Enabled,
	)
	var i DeployMapping
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.AgentID,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMappingService = `-- name: CreateMappingService :exec
INSERT INTO deploy_mapping_services (mapping_id, name, image, tag, position)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMappingServiceParams struct {
	MappingID pgtype.UUID `json:"mapping_id"`
	Name      string      `json:"name"`
	Image     string      `json:"image"`
	Tag       string      `json:"tag"`
	Position  int32       `json:"position"`
}

func (q *Queries) CreateMappingService(ctx context.Context, arg CreateMappingServiceParams) error {
	_, err := q.db.Exec(ctx, createMappingService,
		arg.MappingID,
		arg.Name,
		arg.Image,
		arg.Tag,
		arg.Position,
	)
	return err
}

const deleteDeployMapping = `-- name: DeleteDeployMapping :one
DELETE FROM deploy_mappings WHERE id = $1 RETURNING id, repo, agent_id, environment, enabled, created_at, updated_at
`

func (q *Queries) DeleteDeployMapping(ctx context.Context, id pgtype.UUID) (DeployMapping, error) {
	row := q.db.QueryRow(ctx, deleteDeployMapping, id)
	var i DeployMapping
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.AgentID,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMappingServicesByMapping = `-- name: DeleteMappingServicesByMapping :exec
DELETE FROM deploy_mapping_services WHERE mapping_id = $1
`

func (q *Queries) DeleteMappingServicesByMapping(ctx context.Context, mappingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMappingServicesByMapping, mappingID)
	return err
}

const getDeployMapping = `-- name: GetDeployMapping :one
SELECT dm.id, dm.repo, dm.agent_id, dm.environment, dm.enabled, dm.created_at, dm.updated_at,
       a.name AS agent_name,
       COALESCE(
           (SELECT jsonb_agg(
                       jsonb_build_object('name', s.name, 'image', s.image, 'tag', s.tag)
                       ORDER BY s.position
                   )
            FROM deploy_mapping_services s
            WHERE s.mapping_id = dm.id),
           '[]'::jsonb
       ) AS services
FROM deploy_mappings dm
JOIN agents a ON a.id = dm.agent_id
WHERE dm.id = $1
`

type GetDeployMappingRow struct {
	ID          pgtype.UUID        `json:"id"`
	Repo        string             `json:"repo"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Environment string             `json:"environment"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AgentName   string             `json:"agent_name"`
	Services    interface{}        `json:"services"`
}

func (q *Queries) GetDeployMapping(ctx context.Context, id pgtype.UUID) (GetDeployMappingRow, error) {
	row := q.db.QueryRow(ctx, getDeployMapping, id)
	var i GetDeployMappingRow
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.AgentID,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentName,
		&i.Services,
	)
	return i, err
}

const listDeployMappings = `-- name: ListDeployMappings :many
SELECT dm.id, dm.repo, dm.agent_id, dm.environment, dm.enabled, dm.created_at, dm.updated_at,
       a.name AS agent_name,
       COALESCE(
           (SELECT jsonb_agg(
                       jsonb_build_object('name', s.name, 'image', s.image, 'tag', s.tag)
                       ORDER BY s.position
                   )
            FROM deploy_mapping_services s
            WHERE s.mapping_id = dm.id),
           '[]'::jsonb
       ) AS services
FROM deploy_mappings dm
JOIN agents a ON a.id = dm.agent_id
ORDER BY dm.repo ASC, dm.created_at ASC
`

type ListDeployMappingsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Repo        string             `json:"repo"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Environment string             `json:"environment"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AgentName   string             `json:"agent_name"`
	Services    interface{}        `json:"services"`
}

func (q *Queries) ListDeployMappings(ctx context.Context) ([]ListDeployMappingsRow, error) {
	rows, err := q.db.Query(ctx, listDeployMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployMappingsRow{}
	for rows.Next() {
		var i ListDeployMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.AgentID,
			&i.Environment,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentName,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledMappingsByRepo = `-- name: ListEnabledMappingsByRepo :many
SELECT dm.id, dm.repo, dm.agent_id, dm.environment, dm.enabled, dm.created_at, dm.updated_at,
       a.name AS agent_name,
       COALESCE(
           (SELECT jsonb_agg(
                       jsonb_build_object('name', s.name, 'image', s.image, 'tag', s.tag)
                       ORDER BY s.position
                   )
            FROM deploy_mapping_services s
            WHERE s.mapping_id = dm.id),
           '[]'::jsonb
       ) AS services
FROM deploy_mappings dm
JOIN agents a ON a.id = dm.agent_id
WHERE LOWER(dm.repo) = LOWER($1)
  AND dm.enabled = true
ORDER BY dm.created_at ASC
`

type ListEnabledMappingsByRepoRow struct {
	ID          pgtype.UUID        `json:"id"`
	Repo        string             `json:"repo"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Environment string             `json:"environment"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AgentName   string             `json:"agent_name"`
	Services    interface{}        `json:"services"`
}

func (q *Queries) ListEnabledMappingsByRepo(ctx context.Context, lower string) ([]ListEnabledMappingsByRepoRow, error) {
	rows, err := q.db.Query(ctx, listEnabledMappingsByRepo, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledMappingsByRepoRow{}
	for rows.Next() {
		var i ListEnabledMappingsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.AgentID,
			&i.Environment,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentName,
			&i.Services,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeployMapping = `-- name: UpdateDeployMapping :one
UPDATE deploy_mappings
SET repo        = $2,
    agent_id    = $3,
    environment = $4,
    enabled     = $5,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, repo, agent_id, environment, enabled, created_at, updated_at
`

type UpdateDeployMappingParams struct {
	ID          pgtype.UUID `json:"id"`
	Repo        string      `json:"repo"`
	AgentID     pgtype.UUID `json:"agent_id"`
	Environment string      `json:"environment"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) UpdateDeployMapping(ctx context.Context, arg UpdateDeployMappingParams) (DeployMapping, error) {
	row := q.db.QueryRow(ctx, updateDeployMapping,
		arg.ID,
		arg.Repo,
		arg.AgentID,
		arg.Environment,
		arg.Enabled,
	)
	var i DeployMapping
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.AgentID,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
