// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_logs.sql

package sqlc

import (
	"context"
)

const createEventLog = `-- name: CreateEventLog :one
INSERT INTO event_logs (delivery_id, event_type, repo, sender, summary)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, delivery_id, event_type, repo, sender, summary, created_at
`

type CreateEventLogParams struct {
	DeliveryID string `json:"delivery_id"`
	EventType  string `json:"event_type"`
	Repo       string `json:"repo"`
	Sender     string `json:"sender"`
	Summary    string `json:"summary"`
}

func (q *Queries) CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, createEventLog,
		arg.DeliveryID,
		arg.EventType,
		arg.Repo,
		arg.Sender,
		arg.Summary,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.EventType,
		&i.Repo,
		&i.Sender,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listEventLogs = `-- name: ListEventLogs :many
SELECT id, delivery_id, event_type, repo, sender, summary, created_at FROM event_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListEventLogs(ctx context.Context, limit int32) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, listEventLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.EventType,
			&i.Repo,
			&i.Sender,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
