// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	ComposeFile string             `json:"compose_file"`
	RemoteIp    string             `json:"remote_ip"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DeployIntent struct {
	ID             pgtype.UUID      `json:"id"`
	DeliveryID     string           `json:"delivery_id"`
	StackIndex     int32            `json:"stack_index"`
	Repo           string           `json:"repo"`
	GitRef         string           `json:"git_ref"`
	Sha            string           `json:"sha"`
	Image          string           `json:"image"`
	Tag            string           `json:"tag"`
	Stack          string           `json:"stack"`
	Services       []string         `json:"services"`
	Environment    string           `json:"environment"`
	DeploymentID   int64            `json:"deployment_id"`
	InstallationID int64            `json:"installation_id"`
	Status         string           `json:"status"`
	Attempts       int32            `json:"attempts"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DispatchedAt   pgtype.Timestamp `json:"dispatched_at"`
}

type DeployMapping struct {
	ID          pgtype.UUID        `json:"id"`
	Repo        string             `json:"repo"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Services    []string           `json:"services"`
	Environment string             `json:"environment"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
