// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeployIntent struct {
	ID             pgtype.UUID      `json:"id"`
	DeliveryID     string           `json:"delivery_id"`
	StackIndex     int32            `json:"stack_index"`
	Repo           string           `json:"repo"`
	GitRef         string           `json:"git_ref"`
	Sha            string           `json:"sha"`
	Image          string           `json:"image"`
	Tag            string           `json:"tag"`
	Stack          string           `json:"stack"`
	Services       []string         `json:"services"`
	Environment    string           `json:"environment"`
	DeploymentID   int64            `json:"deployment_id"`
	InstallationID int64            `json:"installation_id"`
	Status         string           `json:"status"`
	Attempts       int32            `json:"attempts"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DispatchedAt   pgtype.Timestamp `json:"dispatched_at"`
}
