// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	RemoteIp   string             `json:"remote_ip"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ProjectID  pgtype.UUID        `json:"project_id"`
}

type DeployIntent struct {
	ID             pgtype.UUID      `json:"id"`
	DeliveryID     string           `json:"delivery_id"`
	Repo           string           `json:"repo"`
	GitRef         string           `json:"git_ref"`
	Sha            string           `json:"sha"`
	Stack          string           `json:"stack"`
	Environment    string           `json:"environment"`
	DeploymentID   int64            `json:"deployment_id"`
	InstallationID int64            `json:"installation_id"`
	Status         string           `json:"status"`
	Attempts       int32            `json:"attempts"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DispatchedAt   pgtype.Timestamp `json:"dispatched_at"`
	ServicesSpec   []byte           `json:"services_spec"`
	ProjectID      pgtype.UUID      `json:"project_id"`
	ComposeFile    string           `json:"compose_file"`
}

type EventLog struct {
	ID         pgtype.UUID        `json:"id"`
	DeliveryID string             `json:"delivery_id"`
	EventType  string             `json:"event_type"`
	Repo       string             `json:"repo"`
	Sender     string             `json:"sender"`
	Summary    string             `json:"summary"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ComposeFile string             `json:"compose_file"`
	Environment string             `json:"environment"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Name          string             `json:"name"`
	Repo          string             `json:"repo"`
	RootDirectory string             `json:"root_directory"`
	Branch        string             `json:"branch"`
	Image         string             `json:"image"`
	Tag           string             `json:"tag"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
