// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (project_id, user_id, role, added_by)
VALUES ($1, $2, $3, $4)
RETURNING project_id, user_id, role, added_by, created_at
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
	AddedBy   pgtype.UUID `json:"added_by"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.AddedBy,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, added_by, created_at FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.project_id, pm.user_id, pm.role, pm.added_by, pm.created_at,
       u.email AS user_email, u.name AS user_name
FROM project_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY u.email ASC
`

type ListProjectMembersRow struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	AddedBy   pgtype.UUID        `json:"added_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserEmail string             `json:"user_email"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.user_id, p.name, p.description, p.compose_file, p.environment, p.enabled, p.created_at, p.updated_at, u.email AS user_email,
       CASE WHEN p.user_id = $1 THEN 'owner' ELSE 'member' END AS role
FROM projects p
JOIN users u ON u.id = p.user_id
LEFT JOIN project_members pm
  ON pm.project_id = p.id AND pm.user_id = $1
WHERE p.user_id = $1 OR pm.user_id = $1
ORDER BY p.name ASC
`

type ListProjectsForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ComposeFile string             `json:"compose_file"`
	Environment string             `json:"environment"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserEmail   string             `json:"user_email"`
	Role        string             `json:"role"`
}

func (q *Queries) ListProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsForUserRow{}
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ComposeFile,
			&i.Environment,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :one
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
RETURNING project_id, user_id, role, added_by, created_at
`

type RemoveProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}
