// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name, description, compose_file, environment, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at
`

type CreateProjectParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ComposeFile string      `json:"compose_file"`
	Environment string      `json:"environment"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ComposeFile,
		arg.Environment,
		arg.Enabled,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects WHERE id = $1 RETURNING id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByUserAndName = `-- name: GetProjectByUserAndName :one
SELECT id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at FROM projects WHERE user_id = $1 AND name = $2
`

type GetProjectByUserAndNameParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) GetProjectByUserAndName(ctx context.Context, arg GetProjectByUserAndNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUserAndName, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.user_id, p.name, p.description, p.compose_file, p.environment, p.enabled, p.created_at, p.updated_at, u.email AS user_email
FROM projects p
JOIN users u ON u.id = p.user_id
ORDER BY u.email ASC, p.name ASC
`

type ListProjectsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	ComposeFile string             `json:"compose_file"`
	Environment string             `json:"environment"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserEmail   string             `json:"user_email"`
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ComposeFile,
			&i.Environment,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at FROM projects WHERE user_id = $1 ORDER BY name ASC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ComposeFile,
			&i.Environment,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name         = $2,
    description  = $3,
    compose_file = $4,
    environment  = $5,
    enabled      = $6,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ComposeFile string      `json:"compose_file"`
	Environment string      `json:"environment"`
	Enabled     bool        `json:"enabled"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ComposeFile,
		arg.Environment,
		arg.Enabled,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
