// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name, description, compose_file, environment, enabled, compose_project_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at, compose_project_name
`

type CreateProjectParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	ComposeFile        string      `json:"compose_file"`
	Environment        string      `json:"environment"`
	Enabled            bool        `json:"enabled"`
	ComposeProjectName string      `json:"compose_project_name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.ComposeFile,
		arg.Environment,
		arg.Enabled,
		arg.ComposeProjectName,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ComposeProjectName,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects WHERE id = $1 RETURNING id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at, compose_project_name
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ComposeProjectName,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at, compose_project_name FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ComposeProjectName,
	)
	return i, err
}

const getProjectByUserAndName = `-- name: GetProjectByUserAndName :one
SELECT id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at, compose_project_name FROM projects WHERE user_id = $1 AND name = $2
`

type GetProjectByUserAndNameParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) GetProjectByUserAndName(ctx context.Context, arg GetProjectByUserAndNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUserAndName, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ComposeProjectName,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name         = $2,
    description  = $3,
    compose_file = $4,
    environment  = $5,
    enabled      = $6,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, user_id, name, description, compose_file, environment, enabled, created_at, updated_at, compose_project_name
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ComposeFile string      `json:"compose_file"`
	Environment string      `json:"environment"`
	Enabled     bool        `json:"enabled"`
}

// compose_project_name is intentionally not updatable: renaming a project must
// not change the docker-compose --project-name slug, otherwise containers
// started under the old slug are orphaned.
func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ComposeFile,
		arg.Environment,
		arg.Enabled,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.ComposeFile,
		&i.Environment,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ComposeProjectName,
	)
	return i, err
}
