// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	BindAgentToProject(ctx context.Context, arg BindAgentToProjectParams) (Agent, error)
	ClearAgentProjectBinding(ctx context.Context, projectID pgtype.UUID) error
	CompleteDeployIntent(ctx context.Context, arg CompleteDeployIntentParams) (DeployIntent, error)
	CountDeployIntentsByStatus(ctx context.Context, status string) (int64, error)
	// Webhook redeliveries dedup on (delivery_id, project_id) via the partial
	// unique index idx_deploy_intents_delivery_project. On conflict sqlc returns
	// pgx.ErrNoRows, which callers treat as "already enqueued, do nothing".
	CreateDeployIntent(ctx context.Context, arg CreateDeployIntentParams) (DeployIntent, error)
	CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteOldEventLogs(ctx context.Context, offset int32) (int64, error)
	DeleteProject(ctx context.Context, id pgtype.UUID) (Project, error)
	DeleteServiceInProject(ctx context.Context, arg DeleteServiceInProjectParams) (Service, error)
	DeleteServicesByProject(ctx context.Context, projectID pgtype.UUID) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSessionsForUser(ctx context.Context, userID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) (User, error)
	FailTimedOutIntents(ctx context.Context, arg FailTimedOutIntentsParams) ([]DeployIntent, error)
	GetAgent(ctx context.Context, id pgtype.UUID) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetDeployIntentByID(ctx context.Context, id pgtype.UUID) (DeployIntent, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectByUserAndName(ctx context.Context, arg GetProjectByUserAndNameParams) (Project, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error)
	GetService(ctx context.Context, id pgtype.UUID) (Service, error)
	GetSession(ctx context.Context, token string) (Session, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserPasswordHashByEmail(ctx context.Context, lower string) (GetUserPasswordHashByEmailRow, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListDeployIntentsByStatus(ctx context.Context, status string) ([]DeployIntent, error)
	// Webhook matching: returns every service in an enabled project whose repo
	// matches (case-insensitive). The webhook handler still has to filter by
	// root_directory against the pushed file paths before enqueueing intents.
	ListEnabledServicesByRepoAndBranch(ctx context.Context, arg ListEnabledServicesByRepoAndBranchParams) ([]ListEnabledServicesByRepoAndBranchRow, error)
	// workflow_run matching: like ListEnabledServicesByRepoAndBranch but keyed on
	// the workflow filename (e.g. "build-and-publish.yml"). Used when a CI run
	// finishes successfully and we want to deploy the matching services.
	ListEnabledServicesByRepoAndWorkflow(ctx context.Context, arg ListEnabledServicesByRepoAndWorkflowParams) ([]ListEnabledServicesByRepoAndWorkflowRow, error)
	ListEventLogs(ctx context.Context, limit int32) ([]EventLog, error)
	ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error)
	ListProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]ListProjectsForUserRow, error)
	ListRecentDeployIntents(ctx context.Context, limit int32) ([]DeployIntent, error)
	// Same as ListRecentDeployIntents but scoped to projects the user can access:
	// either owns (projects.user_id) or is a member of (project_members).
	ListRecentDeployIntentsForUser(ctx context.Context, arg ListRecentDeployIntentsForUserParams) ([]DeployIntent, error)
	ListServicesByProject(ctx context.Context, projectID pgtype.UUID) ([]Service, error)
	ListUsers(ctx context.Context) ([]User, error)
	RefreshSession(ctx context.Context, arg RefreshSessionParams) error
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (ProjectMember, error)
	RequeueDeployIntent(ctx context.Context, id pgtype.UUID) (DeployIntent, error)
	RequeueTimedOutIntents(ctx context.Context, arg RequeueTimedOutIntentsParams) ([]DeployIntent, error)
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error
	// Claim the oldest dispatchable intent for @agent_name's bound project.
	// FOR UPDATE SKIP LOCKED + the dispatched-stack guard keep concurrent
	// pollers from blocking each other or double-claiming a stack.
	TakeNextDeployIntent(ctx context.Context, agentName string) (DeployIntent, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// agent_type and version are passed in (empty string treated as NULL). On
	// conflict we preserve the existing value when the caller didn't send one,
	// so an old agent reconnecting without the header doesn't wipe known data.
	UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error)
}

var _ Querier = (*Queries)(nil)
