// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, password_is_bootstrap)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, created_at, updated_at, password_hash, password_is_bootstrap
`

type CreateUserParams struct {
	Email               string `json:"email"`
	Name                string `json:"name"`
	PasswordHash        string `json:"password_hash"`
	PasswordIsBootstrap bool   `json:"password_is_bootstrap"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.PasswordIsBootstrap,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordIsBootstrap,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1 RETURNING id, email, name, created_at, updated_at, password_hash, password_is_bootstrap
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordIsBootstrap,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at, updated_at, password_hash, password_is_bootstrap FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordIsBootstrap,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at, updated_at, password_hash, password_is_bootstrap FROM users WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordIsBootstrap,
	)
	return i, err
}

const getUserPasswordHashByEmail = `-- name: GetUserPasswordHashByEmail :one
SELECT id, email, password_hash FROM users WHERE LOWER(email) = LOWER($1)
`

type GetUserPasswordHashByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetUserPasswordHashByEmail(ctx context.Context, lower string) (GetUserPasswordHashByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHashByEmail, lower)
	var i GetUserPasswordHashByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, created_at, updated_at, password_hash, password_is_bootstrap FROM users ORDER BY email ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
			&i.PasswordIsBootstrap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users
SET password_hash         = $2,
    password_is_bootstrap = $3,
    updated_at            = NOW()
WHERE id = $1
`

type SetUserPasswordHashParams struct {
	ID                  pgtype.UUID `json:"id"`
	PasswordHash        string      `json:"password_hash"`
	PasswordIsBootstrap bool        `json:"password_is_bootstrap"`
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setUserPasswordHash, arg.ID, arg.PasswordHash, arg.PasswordIsBootstrap)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email      = $2,
    name       = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, created_at, updated_at, password_hash, password_is_bootstrap
`

type UpdateUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordIsBootstrap,
	)
	return i, err
}
